server:
  port: 8050
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka  ## 注册到 eureka
  instance:
    preferIpAddress: true
spring:
  application:
    name: movie-customer
  thymeleaf: # THYMELEAF 
    encoding : UTF-8
    cache : false # 热部署静态文件
    mode : HTML5 # 使用HTML5标准
  feign:
    hystrix:
    # feign熔断器开关
    enabled: true