server:
  port: 8050
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka  ## 注册到 eureka
  instance:
    preferIpAddress: true
spring:
  application:
    name: movie-customer
feign:
    hystrix:
      # feign熔断器开关
      enabled: true