server:
  port: 8060

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka  ## 注册到 eureka 
spring:
  application:
    name: user-provider  ## 应用程序名称，后面会在消费者中用到